runtime: python313
service: default

env_variables:
  SECRET_KEY: "change-this-in-production"
  # Add your API keys here or use Secret Manager
  # FACEBOOK_PAGE_ID: "your-page-id"
  # FACEBOOK_ACCESS_TOKEN: "your-token"
  # OPENAI_API_KEY: "your-openai-key"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Health check configuration
liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300